# Generated by Django 4.0.2 on 2022-02-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='dt_criacao',
            new_name='data_criacao',
        ),
    ]
